#!/usr/bin/env python3
# Copyright 2021 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
"""End-to-end tests for the standalone Cast sender and receiver executables.

This script ensures that the basic functionality of these executables is not
impaired, such as the TLS/UDP connections and encoding and decoding video.
"""

import argparse
from collections import namedtuple
from enum import IntEnum
from enum import IntFlag
import logging
import os
import pathlib
import socket
import ssl
import subprocess
import shutil
import sys
import time
import unittest


# Environment variables that can be overridden to set test properties.
ROOT_ENVVAR = 'OPENSCREEN_ROOT_DIR'
BUILD_ENVVAR = 'OPENSCREEN_BUILD_DIR'
LIBAOM_ENVVAR = 'OPENSCREEN_HAVE_LIBAOM'

# 10 second long example video.
TEST_VIDEO_NAME = 'bbb_sunflower_2160p_60fps_normal.mp4'

# Plenty of padding for playing out the video.
PROCESS_TIMEOUT = 60  # seconds

# Open Screen test certificates expire after 3 days. We crop this slightly (by
# 8 hours) to account for potential errors in time calculations.
CERT_EXPIRY_AGE = (3 * 24 - 8) * 60 * 60

# Default ports for the standalone Cast sender and receiver. These are based on
# the default ports used in Open Screen.
DEFAULT_TCP_PORT = 8010
DEFAULT_UDP_PORT = 2344

# These properties are based on compiled settings in Open Screen, and should
# not change without updating this file.
TEST_CERT_NAME = 'generated_root_cast_receiver.crt'
TEST_KEY_NAME = 'generated_root_cast_receiver.key'
SENDER_BINARY_NAME = 'cast_sender'
RECEIVER_BINARY_NAME = 'cast_receiver'

EXPECTED_RECEIVER_MESSAGES = [
    'CastService is running.',
    'Found codec: opus (known to FFMPEG as opus)',
    'Successfully negotiated a session, creating players.',
]


class VideoCodec(IntEnum):
    """An enumeration of the video codecs that should be sent by the sender."""

    VP8 = 0
    VP9 = 1
    AV1 = 2
    H264 = 3
    HEVC = 4


VIDEO_CODEC_SPECIFIC_RECEIVER_MESSAGES = [
    'Found codec: vp8 (known to FFMPEG as vp8)',
    'Found codec: vp9 (known to FFMPEG as vp9)',
    'Found codec: libaom-av1 (known to FFMPEG as av1)',
    'Found codec: h264 (known to FFMPEG as h264)',
    'Found codec: hevc (known to FFMPEG as hevc)',
]

EXPECTED_SENDER_MESSAGES = [
    'Launching Mirroring App on the Cast Receiver',
    'Max allowed media bitrate (audio + video) will be',
    TEST_VIDEO_NAME + ' (starts in one second)...',
    'The video capturer has reached the end of the media stream.',
    'The audio capturer has reached the end of the media stream.',
    'Video complete. Exiting...',
    'Shutting down...',
]

MISSING_LOG_MESSAGE = """Missing an expected message from either the sender
or receiver. This either means that one of the binaries misbehaved, or you
changed or deleted one of the log messages used for validation. Please ensure
that the necessary log messages are left unchanged, or update this
test suite's expectations."""

DESCRIPTION = """Runs end to end tests for the standalone Cast Streaming sender
and receiver. By default, this script assumes it is being ran from a current
working directory inside Open Screen's source directory, and uses
<root_dir>/out/Default as the build directory. To override these, set the
OPENSCREEN_ROOT_DIR and OPENSCREEN_BUILD_DIR environment variables. If the root
directory is set and the build directory is not,
<OPENSCREEN_ROOT_DIR>/out/Default will be used. In addition, if LibAOM is
installed, one can choose to run AV1 tests by defining the
OPENSCREEN_HAVE_LIBAOM environment variable.

See below for the the help output generated by the `unittest` package."""


def _wait_for_port_available(port=DEFAULT_TCP_PORT,
                             host='127.0.0.1',
                             timeout=5):
    """Wait until both TCP control and UDP streaming ports can be bound."""
    start_time = time.time()
    while time.time() - start_time < timeout:
        tcp_ok = False
        udp_ok = False
        try:
            with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
                s.bind((host, port))
                tcp_ok = True
            with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as s:
                s.bind((host, DEFAULT_UDP_PORT))
                udp_ok = True
        except OSError:
            pass
        if tcp_ok and udp_ok:
            # Add small 0.2s grace period for kernel state settling
            time.sleep(0.2)
            return True
        time.sleep(0.1)
    return False

def _set_log_level(is_verbose):
    """Sets the logging level, either DEBUG or ERROR as appropriate."""
    level = logging.DEBUG if is_verbose else logging.INFO
    logging.basicConfig(stream=sys.stdout, level=level)


def _get_loopback_adapter_name():
    """Retrieves the name of the loopback adapter (lo on Linux/lo0 on Mac)."""
    if sys.platform in ('linux', 'linux2'):
        return 'lo'
    if sys.platform == 'darwin':
        return 'lo0'
    return None


def _get_file_age_in_seconds(path):
    """Get the age of a given file in seconds"""
    # Time is stored in seconds since epoch
    file_last_modified = 0
    if path.exists():
        file_last_modified = path.stat().st_mtime
    return time.time() - file_last_modified


def _get_build_paths():
    """Gets the root and build paths (either default or from the environment

  variables), and sets related paths to binaries and files.
  """
    root_path = pathlib.Path(
        os.environ[ROOT_ENVVAR] if os.getenv(ROOT_ENVVAR) else subprocess.
        getoutput('git rev-parse --show-toplevel'))
    assert root_path.exists(), 'Could not find openscreen root!'

    build_path = (pathlib.Path(os.environ[BUILD_ENVVAR])
                  if os.getenv(BUILD_ENVVAR) else root_path.joinpath(
                      'out', 'Default').resolve())
    assert build_path.exists(), 'Could not find openscreen build!'

    BuildPaths = namedtuple('BuildPaths',
                            'root build test_video cast_receiver cast_sender')
    return BuildPaths(
        root=root_path,
        build=build_path,
        test_video=build_path.joinpath(TEST_VIDEO_NAME).resolve(),
        cast_receiver=build_path.joinpath(RECEIVER_BINARY_NAME).resolve(),
        cast_sender=build_path.joinpath(SENDER_BINARY_NAME).resolve(),
    )


class TestFlags(IntFlag):
    """Test flags, primarily used to control sender and receiver configuration

  to test different features of the standalone libraries.
  """

    USE_REMOTING = 1
    USE_ANDROID_HACK = 2


class StandaloneCastTest(unittest.TestCase):
    """Test class for setting up and running end to end tests on the

  standalone sender and receiver binaries. This class uses the unittest
  package, so methods that are executed as tests all have named prefixed
  with "test_".

  This suite sets the current working directory to the root of the Open
  Screen repository, and references all files from the root directory.
  Generated certificates should always be in |cls.build_paths.root|.
  """

    @classmethod
    def setUpClass(cls):
        """Shared setup method for all tests, handles one-time updates."""
        cls.build_paths = _get_build_paths()
        os.chdir(cls.build_paths.root)
        cls.setup_video()
        cls.generate_certificates()

    @classmethod
    def setup_video(cls):
        """Copies the test video from the test data folder."""
        if os.path.exists(cls.build_paths.test_video):
            logging.debug('Video already exists, skipping copy...')
            return

        source_path = cls.build_paths.root / 'test/data/cast' / TEST_VIDEO_NAME
        if not source_path.exists():
            raise FileNotFoundError(
                f'Could not find test video at {source_path}')

        logging.debug('Copying video from %s', source_path)
        shutil.copy(source_path, cls.build_paths.test_video)

    @classmethod
    def generate_certificates(cls):
        """Generates test certificates using the cast receiver."""
        cert_age = _get_file_age_in_seconds(pathlib.Path(TEST_CERT_NAME))
        key_age = _get_file_age_in_seconds(pathlib.Path(TEST_KEY_NAME))
        if cert_age < CERT_EXPIRY_AGE and key_age < CERT_EXPIRY_AGE:
            logging.debug('Credentials are up to date...')
            return

        logging.debug('Credentials out of date, generating new ones...')
        command = [
            cls.build_paths.cast_receiver,
            '-g',  # Generate certificate and private key.
            '-v',  # Enable verbose logging.
        ]
        try:
            subprocess.check_output(command, stderr=subprocess.STDOUT)
        except subprocess.CalledProcessError as error:
            print('Generation failed with output: ', error.output.decode())
            raise

    def launch_receiver(self):
        """Launches the receiver process with discovery disabled."""
        logging.debug('Launching the receiver application...')
        self.assertTrue(_wait_for_port_available(8010),
                        'Port 8010 not available before launching receiver!')
        loopback = _get_loopback_adapter_name()
        self.assertTrue(loopback)

        command = [
            self.build_paths.cast_receiver,
            '-d',
            TEST_CERT_NAME,
            '-p',
            TEST_KEY_NAME,
            '-x',  # Skip discovery, only necessary on Mac OS X.
            '-v',  # Enable verbose logging.
            '-P',  # enable Perfetto based performance logging.
            loopback,
        ]
        return subprocess.Popen(command,
                                stdout=subprocess.PIPE,
                                stderr=subprocess.PIPE)

    def launch_sender(self, flags, codec=None):
        """Launches the sender process, running the test video file once."""
        logging.debug('Launching the sender application...')
        command = [
            self.build_paths.cast_sender,
            '127.0.0.1:8010',
            self.build_paths.test_video,
            '-d',
            TEST_CERT_NAME,
            '-n',  # Only play the video once, and then exit.
            '-P',  # enable Perfetto based performance logging.
        ]
        if TestFlags.USE_ANDROID_HACK in flags:
            command.append('-a')
        if TestFlags.USE_REMOTING in flags:
            command.append('-r')

        # The standalone sender sends VP8 if no codec command line argument is
        # passed.
        if codec:
            command.append('-c')
            if codec == VideoCodec.VP8:
                command.append('vp8')
            elif codec == VideoCodec.VP9:
                command.append('vp9')
            elif codec == VideoCodec.AV1:
                command.append('av1')
            elif codec == VideoCodec.H264:
                command.append('h264')
            elif codec == VideoCodec.HEVC:
                command.append('hevc')

        # pylint: disable = consider-using-with
        return subprocess.Popen(command,
                                stdout=subprocess.PIPE,
                                stderr=subprocess.PIPE)

    def check_logs(self, logs, codec=None):
        """Checks that the outputted logs contain expected behavior."""

        # If a codec was not provided, we should make sure that the standalone
        # sender sent VP8.
        if codec is None:
            codec = VideoCodec.VP8

        for message in EXPECTED_RECEIVER_MESSAGES + [
                VIDEO_CODEC_SPECIFIC_RECEIVER_MESSAGES[codec]
        ]:
            self.assertTrue(
                message in logs[0],
                f'Missing log message: {message}.\n{MISSING_LOG_MESSAGE}',
            )
        for message in EXPECTED_SENDER_MESSAGES:
            self.assertTrue(
                message in logs[1],
                f'Missing log message: {message}.\n{MISSING_LOG_MESSAGE}',
            )
        for log in logs:
            for prefix in ['[ERROR:', '[FATAL:']:
                if prefix in log:
                    lines = log.splitlines()
                    for i, line in enumerate(lines):
                        if prefix in line:
                            print(f'Found error line: {line}')
                            for j in range(1, 10):
                                if i + j < len(lines): print(lines[i + j])
                self.assertTrue(prefix not in log,
                                f'Logs contained an error: {prefix}')
        logging.debug('Finished validating log output')

    def get_output(self, flags, codec=None):
        """Launches the sender and receiver, and handles exit output."""
        receiver_process = self.launch_receiver()
        logging.debug('Letting the receiver start up...')
        time.sleep(3)
        sender_process = self.launch_sender(flags, codec)

        logging.debug(
            'Launched sender PID %i and receiver PID %i...',
            sender_process.pid,
            receiver_process.pid,
        )
        logging.debug('collating output...')

        try:
            # We wait for the sender to complete, as it drives the session.
            sender_out, sender_err = sender_process.communicate(
                timeout=PROCESS_TIMEOUT)

            # Give the receiver a moment to process any final messages / settle.
            time.sleep(2)

            # The receiver might not exit automatically, so we terminate it.
            receiver_process.terminate()
            try:
                receiver_process.wait(timeout=5)
            except subprocess.TimeoutExpired:
                receiver_process.kill()

            receiver_out, receiver_err = receiver_process.communicate()

            # Programmatically confirm that the OS released the socket port.
            self.assertTrue(_wait_for_port_available(8010),
                            'Port 8010 not released after receiver shutdown!')

            if TestFlags.USE_REMOTING not in flags:
                self.assertEqual(sender_process.returncode, 0,
                                 'sender had non-zero exit code')

            return (
                receiver_err.decode('utf-8', errors='replace'),
                sender_err.decode('utf-8', errors='replace'),
            )
        except subprocess.TimeoutExpired:
            logging.error('Test timed out, killing processes...')
            receiver_process.kill()
            sender_process.kill()
            receiver_out, receiver_err = receiver_process.communicate()
            sender_out, sender_err = sender_process.communicate()
            logging.error('Receiver Stderr: %s',
                          receiver_err.decode('utf-8', errors='replace'))
            logging.error('Sender Stderr: %s',
                          sender_err.decode('utf-8', errors='replace'))
            raise
        finally:
            if receiver_process.poll() is None:
                receiver_process.kill()
            if sender_process.poll() is None:
                sender_process.kill()

    def test_golden_case(self):
        """Tests that when settings are normal, things work end to end."""
        output = self.get_output([])
        self.check_logs(output)

    def test_remoting(self):
        """Tests that basic remoting works."""
        output = self.get_output(TestFlags.USE_REMOTING)
        self.check_logs(output)

    def test_with_android_hack(self):
        """Tests that things work when the Android RTP hack is enabled."""
        output = self.get_output(TestFlags.USE_ANDROID_HACK)
        self.check_logs(output)

    def test_vp8_flag(self):
        """Tests that the VP8 flag works with standard settings."""
        output = self.get_output([], VideoCodec.VP8)
        self.check_logs(output, VideoCodec.VP8)

    def test_vp9_flag(self):
        """Tests that the VP9 flag works with standard settings."""
        output = self.get_output([], VideoCodec.VP9)
        self.check_logs(output, VideoCodec.VP9)

    @unittest.skipUnless(os.getenv(LIBAOM_ENVVAR),
                         'Skipping AV1 test since LibAOM not installed.')
    def test_av1_flag(self):
        """Tests that the AV1 flag works with standard settings."""
        output = self.get_output([], VideoCodec.AV1)
        self.check_logs(output, VideoCodec.AV1)

    def test_h264_flag(self):
        """Tests that the H264 flag works with standard settings."""
        output = self.get_output([], VideoCodec.H264)
        self.check_logs(output, VideoCodec.H264)

    def test_hevc_flag(self):
        """Tests that the HEVC flag works with standard settings."""
        output = self.get_output([], VideoCodec.HEVC)
        self.check_logs(output, VideoCodec.HEVC)


def _parse_args():
    """Parses the command line arguments and sets up the logging module."""
    # NOTE for future developers: the `unittest` module will complain if it is
    # passed any args that it doesn't understand. If any Open Screen-specific
    # command line arguments are added in the future, they should be cropped
    # from sys.argv before |unittest.main()| is called.
    parser = argparse.ArgumentParser(description=DESCRIPTION)
    parser.add_argument('-v',
                        '--verbose',
                        help='enable debug logging',
                        action='store_true')

    parsed_args, remaining_args = parser.parse_known_args(sys.argv[1:])
    _set_log_level(parsed_args.verbose)

    # Crop Open Screen-specific command line arguments from sys.argv before
    # calling unittest.main().
    sys.argv = [sys.argv[0]] + remaining_args


if __name__ == '__main__':
    _parse_args()
    unittest.main()
